apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-config
  namespace: llama-deployment
data:
  MODEL_NAME: "meta-llama/Llama-3.2-3B"
  MAX_TOKENS: "512"
  TEMPERATURE: "0.7"
  BATCH_SIZE: "8"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-deployment
  namespace: llama-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llama-server
  template:
    metadata:
      labels:
        app: llama-server
    spec:
      containers:
      - name: llama-container
        image: your-registry/llama-inference:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: llama-config
        - secretRef:
            name: llama-secrets
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
            nvidia.com/gpu: "1"
          limits:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: model-cache
          mountPath: /root/.cache/huggingface
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: llama-model-cache
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4  # Adjust for your cloud provider
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llama-hpa
  namespace: llama-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llama-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model-cache
  namespace: llama-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
apiVersion: v1
kind: Secret
metadata:
  name: llama-secrets
  namespace: llama-deployment
type: Opaque
data:
  HUGGING_FACE_HUB_TOKEN: eW91cl9oZl90b2tlbg==  # Replace with your token
apiVersion: v1
kind: Service
metadata:
  name: llama-service
  namespace: llama-deployment
spec:
  selector:
    app: llama-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
