apiVersion: v1
kind: Service
metadata:
  name: llama-service
  namespace: llama-deployment
spec:
  selector:
    app: llama-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
