FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip
COPY app/api_gateway/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app/api_gateway/ ./

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

